### ISSUE TITLE
question by code

### ISSUE THREAD

**Issue by AlexeyBee** [yazaabed/react-tabs#17]
https://github.com/YazanAabeed/react-tabs/blob/d97adae6b29f368ed701b0d758ba013620604081/src/components/TabsContext.js#L16

probably meant 'isOldTabFound'?

**Comment by YazanAabeed** [comment]
@AlexeyBee Sorry for being late to answer your question, I was moving to Munich for a new job. Yeah, you are right. Also, it would be much better if it is `isTabExist`.

Thank you for your interest in my component 👍I will fix it and if you like to create a pull request for my component it would be nice.
