### ISSUE TITLE
Any UMD build available at a CDN?

### ISSUE THREAD

**Issue by pateskinasy** [yazaabed/react-tabs#22]
Hi, thanks for this!

Any UMD build available at a CDN?

**Comment by yazaabed** [comment]
@pateskinasy sorry for really late reply. I hope it is still helpful for you. I just updated this package with new build technology and here https://unpkg.com/@feuer/react-tabs@0.1.6/bundles/tabs.umd.min.js you can find the free cdn for loading this component. You can remove .min if you are not interested in the min code. Please let me know if this is helpful and thank you for using this component :)

**Comment by pateskinasy** [comment]
Thanks for reverting @yazaabed . Great job.
